name: dart_ilogger
description: A plug-in based logging interface. This package is not intended to be used for conrete logging purposes, it is primarily for the interfaces. It provides only an extremely basic implementation of a real logger.
version: 1.0.0
publish_to: none #todo(nf): remove eventually
homepage: https://github.com/0xnf/dart_ilogger

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: { build_runner: ^2.2.0, json_serializable: ^6.3.1 , path: ^1.8.3}
